# Generated by Django 3.2.7 on 2021-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0002_alter_arbiterprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='arbiter',
        ),
        migrations.AddField(
            model_name='specialization',
            name='arbiter',
            field=models.ManyToManyField(related_name='specializations', to='arbiter.ArbiterProfile'),
        ),
    ]
