# Generated by Django 3.2.7 on 2021-10-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0003_auto_20211002_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='arbiter',
            field=models.ManyToManyField(blank=True, null=True, related_name='specializations', to='arbiter.ArbiterProfile'),
        ),
    ]
