# Generated by Django 3.2.7 on 2021-10-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0004_alter_specialization_arbiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbiterprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
