# Generated by Django 3.2.7 on 2021-10-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0005_arbiterprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='arbiter',
        ),
        migrations.AddField(
            model_name='language',
            name='arbiter',
            field=models.ManyToManyField(blank=True, null=True, related_name='languages', to='arbiter.ArbiterProfile'),
        ),
    ]
