# Generated by Django 3.2.7 on 2021-10-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0007_auto_20211002_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('arbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbiter.arbiterprofile')),
            ],
        ),
    ]
