# Generated by Django 3.2.7 on 2021-10-02 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0009_auto_20211002_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='town',
        ),
        migrations.AddField(
            model_name='court',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arbiter.location'),
        ),
        migrations.AlterField(
            model_name='arbiterprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arbiter.location'),
        ),
    ]
