# Generated by Django 3.2.7 on 2021-10-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0011_auto_20211003_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbiterprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
